const REMOVED_FIELDS = new Set(['brOfSvc']);

const PERSONNEL_FIELD_MAP = {
  fullName: 'full_name',
  nameLast: 'name_last',
  nameFirst: 'name_first',
  nameMiddle: 'name_middle',
  organization: 'organization',
  presentJob: 'present_job',
  businessAddress: 'business_address',
  homeAddress: 'home_address',
  dateOfBirth: 'date_of_birth',
  placeOfBirth: 'place_of_birth',
  changeInName: 'change_in_name',
  nicknames: 'nicknames',
  nationality: 'nationality',
  taxId: 'tax_id',
  telNo: 'tel_no',
  mobile: 'mobile',
  email: 'email',
  passportNr: 'passport_nr',
  passportExpiry: 'passport_expiry',
  sex: 'sex',
  age: 'age',
  height: 'height',
  weight: 'weight',
  build: 'build',
  complexion: 'complexion',
  colorEyes: 'color_eyes',
  colorHair: 'color_hair',
  scarMarks: 'scar_marks',
  healthState: 'health_state',
  recentIllness: 'recent_illness',
  bloodType: 'blood_type',
  maritalStatus: 'marital_status',
  spouseName: 'spouse_name',
  marriageDatePlace: 'marriage_date_place',
  spouseDob: 'spouse_dob',
  spousePlaceBirth: 'spouse_place_birth',
  spouseOccupation: 'spouse_occupation',
  spouseContact: 'spouse_contact',
  spouseCitizenship: 'spouse_citizenship',
  fatherName: 'father_name',
  fatherDobPlace: 'father_dob_place',
  fatherAddress: 'father_address',
  fatherOccupation: 'father_occupation',
  fatherCitizenship: 'father_citizenship',
  motherName: 'mother_name',
  motherDobPlace: 'mother_dob_place',
  motherAddress: 'mother_address',
  motherOccupation: 'mother_occupation',
  motherCitizenship: 'mother_citizenship',
  siblingsName: 'siblings_name',
  siblingsDob: 'siblings_dob',
  siblingsCitizenship: 'siblings_citizenship',
  siblingsAddress: 'siblings_address',
  siblingsOccupation: 'siblings_occupation',
  siblingsEmployerAddress: 'siblings_employer_address',
  stepParentFullName: 'step_parent_full_name',
  stepParentDob: 'step_parent_dob',
  stepParentAddress: 'step_parent_address',
  stepParentOccupation: 'step_parent_occupation',
  stepParentCitizenship: 'step_parent_citizenship',
  fatherInLawFullName: 'father_in_law_full_name',
  fatherInLawDob: 'father_in_law_dob',
  fatherInLawAddress: 'father_in_law_address',
  fatherInLawOccupation: 'father_in_law_occupation',
  fatherInLawCitizenship: 'father_in_law_citizenship',
  motherInLawFullName: 'mother_in_law_full_name',
  motherInLawDob: 'mother_in_law_dob',
  motherInLawAddress: 'mother_in_law_address',
  motherInLawOccupation: 'mother_in_law_occupation',
  motherInLawCitizenship: 'mother_in_law_citizenship',
  elemLocation: 'elem_location',
  elemAttendance: 'elem_attendance',
  elemGraduated: 'elem_graduated',
  hsLocation: 'hs_location',
  hsAttendance: 'hs_attendance',
  hsGraduated: 'hs_graduated',
  collegeLocation: 'college_location',
  collegeAttendance: 'college_attendance',
  collegeGraduated: 'college_graduated',
  pgLocation: 'pg_location',
  pgCourseAttendance: 'pg_course_attendance',
  pgGraduated: 'pg_graduated',
  otherSchools: 'other_schools',
  civilServiceEligibility: 'civil_service_eligibility',
  dismissedResign: 'dismissed_resign',
  salaryDependent: 'salary_dependent',
  salFiled: 'sal_filed',
  incomeTaxFiled: 'income_tax_filed',
  arrestRecord: 'arrest_record',
  familyArrest: 'family_arrest',
  adminCase: 'admin_case',
  pd1081: 'pd1081',
  liquorDrugs: 'liquor_drugs',
  hobbies: 'hobbies',
  lieDetector: 'lie_detector',
  signedAtCert: 'signed_at_cert',
  signedDateCert: 'signed_date_cert',
  swornDay: 'sworn_day',
  swornMonth: 'sworn_month',
  swornPlace: 'sworn_place',
  residenceCertNr2: 'residence_cert_nr2',
  residenceCertIssuedOn2: 'residence_cert_issued_on2',
  residenceCertIssuedAt2: 'residence_cert_issued_at2',
  administeringOfficer2: 'administering_officer2',
  signatureDataUrl: 'signature_data_url',
  handwrittenEntryDataUrl: 'handwritten_entry_data_url',
  leftThumbMarkDataUrl: 'left_thumb_mark_data_url',
  rightThumbMarkDataUrl: 'right_thumb_mark_data_url',
  photoDataUrl: 'photo_data_url'
};

const CHILD_TABLES = [
  {
    sourceKey: 'children',
    table: 'personnel_children',
    map: { name: 'name', dob: 'dob', citizenshipAddress: 'citizenship_address', fatherMother: 'father_mother' }
  },
  {
    sourceKey: 'placesOfResidence',
    table: 'personnel_places_of_residence',
    map: { inclusiveDates: 'inclusive_dates', address: 'address' }
  },
  {
    sourceKey: 'employmentHistory',
    table: 'personnel_employment_history',
    map: { inclusiveDate: 'inclusive_date', type: 'type', employerAddress: 'employer_address', reasonForLeaving: 'reason_for_leaving' }
  },
  {
    sourceKey: 'seminarsTraining',
    table: 'personnel_seminars_training',
    map: { inclusiveDate: 'inclusive_date', name: 'name', conductedBy: 'conducted_by', remarks: 'remarks' }
  },
  {
    sourceKey: 'foreignCountries',
    table: 'personnel_foreign_countries',
    map: { dateOfVisit: 'date_of_visit', country: 'country', purpose: 'purpose', addressAbroad: 'address_abroad' }
  },
  {
    sourceKey: 'banksCredit',
    table: 'personnel_banks_credit',
    map: { name: 'name', address: 'address', natureOfAccount: 'nature_of_account' }
  },
  { sourceKey: 'creditReferences', table: 'personnel_credit_references', map: { name: 'name', address: 'address' } },
  { sourceKey: 'characterRefs', table: 'personnel_character_refs', map: { name: 'name', address: 'address' } },
  { sourceKey: 'neighbors', table: 'personnel_neighbors', map: { name: 'name', address: 'address' } },
  {
    sourceKey: 'organizations',
    table: 'personnel_organizations',
    map: { organization: 'organization', address: 'address', membershipDate: 'membership_date', positionHeld: 'position_held' }
  },
  {
    sourceKey: 'languages',
    table: 'personnel_languages',
    map: { languageDialect: 'language_dialect', speak: 'speak', read: 'read', write: 'write' }
  }
];

module.exports = {
  REMOVED_FIELDS,
  PERSONNEL_FIELD_MAP,
  CHILD_TABLES
};
